import React from 'react';
import { makeStyles,withStyles } from '@material-ui/core/styles';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemText from '@material-ui/core/ListItemText';
import ListItemAvatar from '@material-ui/core/ListItemAvatar';
import Avatar from '@material-ui/core/Avatar';
import CssBaseline from "@material-ui/core/CssBaseline";
import Paper from "@material-ui/core/Paper";
import Badge from '@material-ui/core/Badge';


const useStyles = makeStyles((theme) => ({
    root: {
      width: '100%',
      maxWidth: '36ch',
      backgroundColor: theme.palette.background.paper,
      display: 'flex',
        '& > *': {
        margin: theme.spacing(1),
      },
    },
    inline: {
      display: 'inline',
    },
}));

const StyledBadge = withStyles((theme) => ({
    badge: {
      backgroundColor: '#44b700',
      color: '#44b700',
      boxShadow: `0 0 0 2px ${theme.palette.background.paper}`,
      '&::after': {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        borderRadius: '50%',
        animation: '$ripple 1.2s infinite ease-in-out',
        border: '1px solid currentColor',
        content: '""',
        display:''
      },
    },
    '@keyframes ripple': {
      '0%': {
        transform: 'scale(.8)',
        opacity: 1,
      },
      '100%': {
        transform: 'scale(2.4)',
        opacity: 0,
      },
    },
  }))(Badge);



export default function FollowList() {
    const classes = useStyles();
  
    const messages = [
        {
          id: 1,
          primary: "Brunch this week?",
          secondary:
            "I'll be in the neighbourhood this week. Let's grab a bite to eat",
          person: "/static/images/avatar/5.jpg"
        },
        {
          id: 2,
          primary: "Birthday Gift",
          secondary: `Do you have a suggestion for a good present for John on his work
            anniversary. I am really confused & would love your thoughts on it.`,
          person: "/static/images/avatar/1.jpg"
        },
        {
          id: 3,
          primary: "Recipe to try",
          secondary:
            "I am try out this new BBQ recipe, I think this might be amazing",
          person: "/static/images/avatar/2.jpg"
        },
        {
          id: 4,
          primary: "Yes!",
          secondary: "I have the tickets to the ReactConf for this year.",
          person: "/static/images/avatar/3.jpg"
        },
        {
          id: 5,
          primary: "Doctor's Appointment",
          secondary:
            "My appointment for the doctor was rescheduled for next Saturday.",
          person: "/static/images/avatar/4.jpg"
        },
        {
          id: 6,
          primary: "Discussion",
          secondary: `Menus that are generated by the bottom app bar (such as a bottom
            navigation drawer or overflow menu) open as bottom sheets at a higher elevation
            than the bar.`,
          person: "/static/images/avatar/5.jpg"
        },
        {
          id: 7,
          primary: "Summer BBQ",
          secondary: `Who wants to have a cookout this weekend? I just got some furniture
            for my backyard and would love to fire up the grill.`,
          person: "/static/images/avatar/1.jpg"
        }
      ];

    return (
      <React.Fragment>
        <CssBaseline />
        <Paper square className={classes.paper}>
          <List className={classes.list}>
            {messages.map(({ id, primary, secondary, person }) => (
              <React.Fragment key={id}>
                <ListItem button>
                  <ListItemAvatar>
                    <StyledBadge
                        overlap="circle"
                        anchorOrigin={{
                        vertical: 'bottom',
                        horizontal: 'right',
                        }}
                        variant="dot"
                    >
                        <Avatar alt="Profile Picture" src={person} />
                    </StyledBadge>
                  </ListItemAvatar>
                  <ListItemText secondary={primary}/>
                </ListItem>
              </React.Fragment>
            ))}
          </List>
        </Paper>
      </React.Fragment>
    );
  }